### ISSUE TITLE
el.chopper~ crashes (seg.fault) Max with fixed_increment set to higher values

### ISSUE THREAD

**Issue by snopeusz** [ericlyon/LyonPotpourri3.0-MaxMSP#1]
(Max 7.2.3 64-bit on MacOS 10.11.5)
Crashes when "fixed_increment" is set somewhere above 15.0

[crashlog-el.chopper-max7.txt](https://github.com/ericlyon/LyonPotpourri3.0-MaxMSP/files/310511/crashlog-el.chopper-max7.txt)

**Comment by ericlyon** [comment]
Thank you for the report. Please try the attached external and let me know if the bug is still present.

**Comment by ericlyon** [comment]
[el.chopper~.mxo.zip](https://github.com/ericlyon/LyonPotpourri3.0-MaxMSP/files/310528/el.chopper.mxo.zip)

**Comment by snopeusz** [comment]
For positive values it seems to be secure. Now, I get SEGV for large negative values (below -700.0).  

Also if there is no buffer loaded when turning on audio in Max, el.chopper bursts extremely loud signal, each time different one (and in different channel/s). It smells like getting some random data from memory. It can be dangerous if listened in headphones.

[max7-el.chopper-segv-negative_fixed_inc.txt](https://github.com/ericlyon/LyonPotpourri3.0-MaxMSP/files/310539/max7-el.chopper-segv-negative_fixed_inc.txt)

**Comment by ericlyon** [comment]
Code has been updated to address both issues.

**Comment by snopeusz** [comment]
Could you post compiled external here? I don't have access to dev tools atm. Thank you.

BTW - great tools, my no.1 is shoehorn. Thank you once again.

**Comment by ericlyon** [comment]
Glad you like shoehorn~. That's one of my favorites as well. Newly compiled externals are at: http://disis.music.vt.edu/eric/main/lyonpotpourri/

**Comment by snopeusz** [comment]
now, if there is no buffer name provided it crashes on turning on DSP...

**Comment by ericlyon** [comment]
That's now fixed in the code. It will be awhile before it makes it into the compiled package. chopper~ can't work without a specified buffer in any case, so for now it's best to just avoid that user error.

**Comment by snopeusz** [comment]
A quite radical way for user education... ;-)
